source 'https://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'dashing-contrib', '~> 0.1.6'
gem 'json' # , '~> 1.7.7'
gem 'dotenv'
gem 'gmail'
gem 'octokit'
gem 'nokogiri'
gem 'i18n'
gem 'faraday', '~> 0.9'
gem 'faraday-http-cache'
gem 'activesupport'  # , '3.2.21'
gem 'rspec'
gem 'rspec-mocks'
gem 'travis'
gem 'bunny'
gem 'jenkins_api_client'
gem "sentry-raven", :git => "git@github.com:getsentry/raven-ruby.git"
# gem "sentry-raven", :git => "https://github.com/getsentry/raven-ruby.git"
gem 'rest-client'
gem 'connection_pool'
gem 'twitter'
gem 'typhoeus'

